class Autogenerated {
  int? id;
  String? anneeScolaire;
  int? idUser;
  String? nomParent;
  String? email;
  int? schoolid;
  String? nomEleve;
  String? prenomEleve;
  String? dateNaissance;
  String? lieuNaissance;
  String? classe;
  String? matricule;
  String? ecole;
  String? montantInitial;
  String? fraisOperateur;
  String? fraisEdupay;
  String? montant;
  String? telephone;
  String? reference;
  String? dateTransaction;
  int? statut;
  String? type;

  Autogenerated(
      {this.id,
      this.anneeScolaire,
      this.idUser,
      this.nomParent,
      this.email,
      this.schoolid,
      this.nomEleve,
      this.prenomEleve,
      this.dateNaissance,
      this.lieuNaissance,
      this.classe,
      this.matricule,
      this.ecole,
      this.montantInitial,
      this.fraisOperateur,
      this.fraisEdupay,
      this.montant,
      this.telephone,
      this.reference,
      this.dateTransaction,
      this.statut,
      this.type});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    anneeScolaire = json['annee_scolaire'];
    idUser = json['id_user'];
    nomParent = json['nom_parent'];
    email = json['email'];
    schoolid = json['schoolid'];
    nomEleve = json['nom_eleve'];
    prenomEleve = json['prenom_eleve'];
    dateNaissance = json['date_naissance'];
    lieuNaissance = json['lieu_naissance'];
    classe = json['classe'];
    matricule = json['matricule'];
    ecole = json['ecole'];
    montantInitial = json['montant_initial'];
    fraisOperateur = json['frais_operateur'];
    fraisEdupay = json['frais_edupay'];
    montant = json['montant'];
    telephone = json['telephone'];
    reference = json['reference'];
    dateTransaction = json['date_transaction'];
    statut = json['statut'];
    type = json['type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = id;
    data['annee_scolaire'] = anneeScolaire;
    data['id_user'] = idUser;
    data['nom_parent'] = nomParent;
    data['email'] = email;
    data['schoolid'] = schoolid;
    data['nom_eleve'] = nomEleve;
    data['prenom_eleve'] = prenomEleve;
    data['date_naissance'] = dateNaissance;
    data['lieu_naissance'] = lieuNaissance;
    data['classe'] = classe;
    data['matricule'] = matricule;
    data['ecole'] = ecole;
    data['montant_initial'] = montantInitial;
    data['frais_operateur'] = fraisOperateur;
    data['frais_edupay'] = fraisEdupay;
    data['montant'] = montant;
    data['telephone'] = telephone;
    data['reference'] = reference;
    data['date_transaction'] = dateTransaction;
    data['statut'] = statut;
    data['type'] = type;
    return data;
  }
}